# Generated by Django 2.2 on 2019-04-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='picture_path',
            new_name='picture',
        ),
    ]
