# Generated by Django 2.2 on 2019-04-15 07:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20190412_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('is_secret', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=64, null=True)),
                ('write_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('modify_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.User')),
            ],
        ),
    ]
