# Generated by Django 2.2 on 2019-04-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20190418_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='modify_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='write_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
